### ISSUE TITLE
useRealtimeCursorで複数のユーザーに別々のcustomViewを割り当てたい

### ISSUE THREAD

**Issue by taitotnk** [KitaharaMugiro/Realtimely#2]
こんにちは！
いつもRealtimelyを利用させていただいています！

質問なのですが、useRealtimeCursorで複数のユーザーに別々のcustomViewを割り当てたい場合(firebase authからログイン中のユーザーのプロフィール画像をカスタムビューに割り当てる)にいい方法はありますでしょうか？

```ts
const customView = () => {
    const param: CustomCursorViewParameter = {
      userInfo: {
        color: "yellow",
        avatar: currentUser?.photoURL,
        name: currentUser?.displayName,
      },
    };
    return <CursorIcon userInfo={param.userInfo} />;
  };
```

```ts
<div className={styles.container} onClick={onMouseMove}>
     <main className={styles.main}>{renderCursors(customView)}</main>
</div>
```

上記のようにしても、カーサーの動きは別々に動きますが、当然ながらそれぞれのブラウザでログインしているユーザーだけのアイコンとなってしまいます。
![image](https://user-images.githubusercontent.com/70618595/143044179-9384fde9-cd52-44b0-aaa4-2d78125eba9a.png)

**Comment by KitaharaMugiro** [comment]
コメントありがとうございます。検討してみますので1日お待ちください

**Comment by KitaharaMugiro** [comment]
@Taito-Code 
検討してみました。
現状の機能から見ると、Taitoさんのやりたいことを実現するのは難しそうです。

カスタムカーソルは以下のように使います、

```
const customView = (param: CustomCursorViewParameter) => {
    return (<CustomCursor userInfo={param.userInfo} />)
}

return (
  <div>
    {renderCursors(customView)}
  </div>
);
```

しかし、ここのCustomCursorViewParameterは以下の情報しか持っていません。

```
export type CustomCursorViewParameter = {
    userInfo: UserInfo
}

type UserInfo = {
    color: string, avatar: string, name: string
}
```

このUserInfoの中にRealtimelyのUserIdを持っていればTaitoさんの方でFirebaseのユーザデータを検索してカスタムビューを作ることが可能です。
その際は以下のような流れになります。

① CustomCursorViewParameterからRealtimely User Idを取得する
② Realtimely User IdからFirebase User Idを取得する
③ Firebase User Idからユーザの情報(名前、アイコンURLなど)を取得する
④ その情報でカスタムビューを作る

もしこの実装ができそうであれば、UserInfoにuserIdを入れる修正をいたします(目安としては１〜２週間ほどお待ちいただくと思います)
それまではuserIdではなくnameを使って上記の実装ができるか検討してみてください。
nameは完全な一意ではないですが、かなり種類があるので擬似的に一意だと思って使えると思います。

**Comment by taitotnk** [comment]
@KitaharaMugiro 
ご検討いただきありがとうございます！

実装できそうなため、修正していただけると幸いです🙇‍♂️

2つ質問なのですが、
` customView ` の引数の `param` はこちらから指定する必要は無いのでしょうか？それともカスタムのために指定する必要があるのでしょうか？

また、
` ② Realtimely User IdからFirebase User Idを取得する `
こちらについてあまり理解できていないのですが、 `Realtimely User Id`は個々の `Cursor` に別々のidが付与され、そこに `Firebase User Id` を紐付けるという認識であってますでしょうか？

何卒アドバイスいただけますと幸いです。
よろしくおねがいします🙏

※補足
私達のプロジェクトでは Firebase auth で Googleアカウントでのログインを使用しています.

**Comment by KitaharaMugiro** [comment]
@Taito-Code 
了解しました。実装完了しましたらご連絡しますね。

質問に回答します。

> customView の引数の param はこちらから指定する必要は無いのでしょうか？それともカスタムのために指定する必要があるのでしょうか？

paramはRealtimelyから渡します。paramを利用してカスタムビューを作ってもらう形になります。
試しに、paramをconsole.logで出力していただくとイメージしやすいかと思います。

> こちらについてあまり理解できていないのですが、 Realtimely User Idは個々の Cursor に別々のidが付与され、そこに Firebase User Id を紐付けるという認識であってますでしょうか？

はい、あっています。
Realtimelyでカーソル情報をpushする際にカスタムの値も同時に送れるようにするか検討しています。もしこれができれば、カスタムの値にfirebase user idを入れておけば、カーソルにfirebase user idを付与することができるので、taitoさんがやりたいことがやりやすくなるのではないかと思います。

どうぞよろしくお願いします。

**Comment by taitotnk** [comment]
回答ありがとうございます！
どうぞよろしくお願いいたします🙇‍♂️

**Comment by KitaharaMugiro** [comment]
@Taito-Code 
お待たせしました。v4.0.0をpublishして、カーソルにカスタム情報を付与できるようにしました。
こちらにfirebaseのuser情報を載せておくことでカスタムビューを作ることができると思います。

https://kitaharamugiro.github.io/Realtimely/jp/docs/api-guide/useRealtimeCursor

**Comment by taitotnk** [comment]
@KitaharaMugiro 
早急に対応していただきありがとうございます🙇‍♂️
ドキュメントの追加も本当にありがとうございます！
これから実装に取り掛かろうと思います！

もしかしたら実装をしている中でまた質問をするかもしれないですが大丈夫でしょうか？🙏

**Comment by KitaharaMugiro** [comment]
@Taito-Code おーけーです！

**Comment by taitotnk** [comment]
@KitaharaMugiro 
ありがとうございます！
